
#to install run
#sudo apt-get install libcrypto++9v5 libcrypto++9v5-dbg libcrypto++-dev

example1:
	g++ -g3 -ggdb -O0 -Wall -Wextra -Wno-unused -o aesgcm_exOutput aesgcm_example.cpp -lcryptopp
	# arg1: number of columns when printing bytes
	./aesgcm_exOutput 10


example2:
	g++ -g3 -ggdb -O0 -Wall -Wextra -Wno-unused -o AdataOutput Driver.cpp stdafx.cpp -lcryptopp
	./AdataOutput
